### PR TITLE
spin_boss_knives

### PR DESCRIPTION
**Pull request by real-yanziyue**

### CODE REVIEW

**Comment by wrpaape** [comment]
Can you try changing the spinning behavior to more of a windmill-type motion rather than firing the knives along the same trajectory?  We're thinking it needs a little tweak.

**Comment by real-yanziyue** [comment]
This is the best I can do. rotate the knives 45 degrees, otherwise needs completely rewrite boss knives.

**Comment by real-yanziyue** [comment]
The knife is not symmetric as well

**Comment by real-yanziyue** [comment]
No longer needed

**Pull request closed without merging**
